config/routes.rb
Rails.application.routes.draw do
  get 'agencies/approval'
  get 'agencies/:id/approve', :to => 'agencies#approve', :as => 'parvez'

  get 'home/contact_us'
  get 'home/about_us'
  get 'home/home_page'
  get 'pilgrim/:id/new' , to: "pilgrim#new", as: "pilgrim_new"
  
  resources :agents  
  post 'pilgrim/create'
  get 'pilgrim/show'
  get 'pilgrim/index'

  resources :packages
  get 'home/index'
  post 'home/index'
  get 'book_now/:id' , to: "home#book_now", as: "book_now"
  resource :home do
    member do
  get 'home/traveler_dashboard'
  post 'home/traveler_dashboard'
  get 'home/agnet_dashboard'
   end
  end
  
  resources :agencies
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'home/user_dashboard'

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def traveler_dashboard
  end

  def agent_dashboard
  end

  def home_page
  end

  def contact_us
  end

  def about_us
  end

  def book_now
    @package = Package.find params[:id]
  end


def index
   #render "home_page"
  	@a = 0  
  	@agencies = Agency.all
    
    @prices = Pricelimit.select(:price)
    @durations = Package.select(:duration).distinct

=begin
    if params[:agency_id]
    	@packages = Package.where(agency_id: params[:agency_id])
    elsif params[:price]
    	@packages = Package.where(price: params[:price])
    elsif params[:duration]
    	@packages = Package.where(duration: params[:duration])
    else
    	@packages = Package.all
    end    
=end

    @selected_agencies = (params[:agency_ids].present? ? params[:agency_ids] : [])
    @selected_prices = (params[:price_ids].present? ? params[:price_ids] : [])
    @selected_durations = (params[:duration_ids].present? ? params[:duration_ids] : [])

    @packages = Package.all 


    if params[:agency_ids]
      @packages = Package.where("agency_id IN (?)", params[:agency_ids])
    end

    if params[:price_ids]
      #binding.pry
      #@packages = Package.where("price IN (?)", params[:price_ids])
      @packages = Package.where("price >= ? and price <= ?",0, params[:price_ids].collect {|p| p})

    end

    if params[:duration_ids]
      @packages = Package.where("duration IN (?)", params[:duration_ids])
    end

    if params[:agency_ids] && params[:price_ids]
      @packages = Package.where("agency_id IN (?) AND price IN (?)", params[:agency_ids], params[:price_ids])
    end

    if params[:price_ids] && params[:duration_ids]
      @packages = Package.where("price IN (?) AND duration IN (?)", params[:price_ids], params[:duration_ids])  
    end

    if params[:agency_ids] && params[:duration_ids]
      @packages = Package.where("agency_id IN (?) AND duration IN (?)", params[:agency_ids], params[:duration_ids])
    end
    
    if params[:agency_ids] && params[:price_ids] && params[:duration_ids]
      @packages = Package.where("agency_id IN (?) AND price IN (?) AND duration IN (?)", params[:agency_ids], params[:price_ids] ,params[:duration_ids])                     
    end
#binding.pry

    @packages = @packages.paginate(:page => params[:page], :per_page => 4)


  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb
This is About Us Page

app/views/home/agent_dashboard.html.erb
this is agent Dashboard

app/views/home/approve.html.erb
<div class >
<table id="test">
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
         
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        
        <td><%= link_to 'Approve', parvez_path(user) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/book_now.html.erb
<p id="notice"><%= notice %></p>

<div class="container form-group" >

<div class="row">
<div class="col-sm-12">
<div class="col-sm-5">
<h2>Selected Package</h2>
<%= image_tag @package.image.url %>
</div>
<div class="col-sm-6">
<strong>Name</strong>:<%= @package.name %><br/>
<strong>Price</strong>:<%= @package.price %><br/>
<strong>Duration</strong>:<%= @package.duration %><br/>


<%= button_to 'Make Payment',class: "btn btn-primary" %>

<%= button_to 'Cancel',class: "btn btn-default"  %>

</div>
</div>
</div>

app/views/home/contact_us.html.erb
This is Contact Us Page

app/views/home/index.html.erb
<script type="text/javascript">
  function f1(){
    //alert("Hello");
    document.myform.submit(this.form);
  }
</script>
<%= form_tag(home_index_path, :name=>'myform')  do %>
  <div id="sidemenu">
    
    <table class="table table" border="0">
  <tbody>
    <tr><th width="60%">Agency</th><th><%= link_to "Clear Filter", home_index_path() %></th></tr> 
    <% @agencies.each do |agency| %>
      <tr>
        <td colspan=2>
<%= check_box_tag "agency_ids[]", agency.id, @selected_agencies.include?(agency.id.to_s), :onclick => "javascript: f1();" %><%=agency.name %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<table class="table table" border="0">
  <tbody>
    <tr><th width="60%">PriceRange</th><th><%= link_to "Clear Filter", home_index_path() %></th>
    </tr>  
    <% @prices.each do |price| %>
      <tr>
        <td>
<%= check_box_tag "price_ids[]", price.price, @selected_prices.include?(price.price.to_s), :onclick => "javascript: f1();" %><%=price.price - 5000%> - <%=price.price %>


        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<table class="table table" border="0">
  <tbody>
    <tr><tr><th width="60%">Duration</th><th><%= link_to "Clear Filter", home_index_path() %></th></tr>  
    <% @durations.each do |duration| %>
      <tr>
        <td>
        <%= check_box_tag "duration_ids[]", duration.duration, @selected_durations.include?(duration.duration.to_s), :onclick => "javascript: f1();" %><%=duration.duration %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>


<div id="content">

<div id="my-posts">    
 <table class="table table-bordered" border="0">
  <tbody>
      <tr>
    <% @packages.each do |package| %>
    <% @a = @a +1 %>
        <td width="311" height="200"><h3><%= Agency.find(package.agency_id).name %></h3><center><%= image_tag package.image.url %></center><h2><%= package.name %></h2><p>Price: <%= package.price %></p><p>Duration: <%= package.duration %></p><p>Some description goes here for each package....</p>
        <%= link_to "Book Now", pilgrim_new_path(package), class: "btn btn-primary" %></td>

    <% if @a ==2 %>
    </tr>
    <tr>
    <% end %>
    <% end %>
      </tr>
  </tbody>
</table>
<% end %>
</div>

<div id="with-button">
    <center><%= will_paginate @packages, :params => {:agency_ids => params[:agency_ids],:price_ids => params[:price_ids],:duration_ids => params[:duration_ids] }, renderer: BootstrapPagination::Rails %></center>
</div>

app/views/home/index.js.erb
$('#my-posts').append('<%= j render @packages %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @packages %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/home/traveler_dashboard.html.erb
This is Traveler History