config/routes.rb
Rails.application.routes.draw do
  get 'agencies/approval'
  get 'agencies/:id/approve', :to => 'agencies#approve', :as => 'parvez'

  get 'home/contact_us'
  get 'home/about_us'
  get 'home/home_page'
  get 'pilgrim/:id/new' , to: "pilgrim#new", as: "pilgrim_new"
  
  resources :agents  
  post 'pilgrim/create'
  get 'pilgrim/show'
  get 'pilgrim/index'

  resources :packages
  get 'home/index'
  post 'home/index'
  get 'book_now/:id' , to: "home#book_now", as: "book_now"
  resource :home do
    member do
  get 'home/traveler_dashboard'
  post 'home/traveler_dashboard'
  get 'home/agnet_dashboard'
   end
  end
  
  resources :agencies
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'home/user_dashboard'

  root 'home#index'

end

app/models/agency.rb
class Agency < ActiveRecord::Base
	has_many :packages, dependent: :destroy
	belongs_to :agent
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
  end

  def approval
    @agents = Agent.where(:approve=> false)
  end

  def approve

    @agent = Agent.find params[:id]
    if @agent.update!(:approve => true)
    @agent.user.add_role :agent

    #LifesaverMailer.approval_mail(@users).deliver_now

    redirect_to agencies_approval_path
  end
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit

  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      params.require(:agency).permit(:name, :phone, :address)
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.erb
<%= form_for(@agency) do |f| %>
  <% if @agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
      <% @agency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agencies/approval.html.erb
<div class >
<table id="test">
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
         
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @agents.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        
        <td><%= link_to 'Approve', parvez_path(user) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/agencies/edit.html.erb
<h1>Editing Agency</h1>

<%= render 'form' %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h3>Listing Agencies</h3>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Agency Name</th>
      <th>Phone</th>
      <th>Address</th>      
      <th></th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agencies.each do |agency| %>
      <tr>
        <td><%= agency.name %></td>
        <td><%= agency.phone %></td>
        <td><%= agency.address %></td>
        <div class="btn-group">
        <td><%= link_to 'Show', agency ,:class => "btn btn-warning" %></td>
        <td><%= link_to 'Edit', edit_agency_path(agency),:class => "btn btn-primary"  %></td>
        <td><%= link_to 'Destroy', agency,:class => "btn btn-danger" , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Agency', new_agency_path,class: "btn btn-success" %>
</div>

app/views/agencies/new.html.erb
<h1>New Agency</h1>

<%= render 'form' %>

<%= link_to 'Back', agencies_path %>

app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @agency.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @agency.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @agency.address %>
</p>

<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>