config/routes.rb
Rails.application.routes.draw do
  get 'agencies/approval'
  get 'agencies/:id/approve', :to => 'agencies#approve', :as => 'parvez'

  get 'home/contact_us'
  get 'home/about_us'
  get 'home/home_page'
  get 'pilgrim/:id/new' , to: "pilgrim#new", as: "pilgrim_new"
  
  resources :agents  
  post 'pilgrim/create'
  get 'pilgrim/show'
  get 'pilgrim/index'

  resources :packages
  get 'home/index'
  post 'home/index'
  get 'book_now/:id' , to: "home#book_now", as: "book_now"
  resource :home do
    member do
  get 'home/traveler_dashboard'
  post 'home/traveler_dashboard'
  get 'home/agnet_dashboard'
   end
  end
  
  resources :agencies
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'home/user_dashboard'

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelSure</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

  <%= csrf_meta_tags %>
<style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
#header{
  margin: 1% auto;
  width:90%;
  height: 20%;
  border-left:1px;
}
  
#sidemenu{
  background-color:#CCCCCC;
  margin: 0% 0.5% 1% 5%;
  width:22%;
  height: 60%;
  float: left;  
}
  
#content{
  margin: 0% 5% 1% 0.5%;
  width:67%;
  height: 60%;
  float: left;
}
  
#footer{
  background-color:cyan;
  margin: 0% 5% 1% 5%;
  width:90%;
  height: 16%;
  float: left;
} 
</style>  
</head>
<body>
  <div id="header">

<nav class="navbar navbar-dark bg-primary">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" >
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'UmrahHajjOnline.com', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Agencies",agencies_path%> <span class="sr-only">(current)</span></a></li>
        <li><%=link_to "Packages"%></li>
        <li><%=link_to "Contact Us",home_contact_us_path%></li>
        <li><%=link_to "About Us",home_about_us_path%></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">

<% 
=begin %><% if user_signed_in? %>     
 <% if current_user.role=="admin" %>
 <%= link_to "Super Admin Dashboard", rails_admin_path %>
 <% elsif current_user.role=="agent" %>
  <%= link_to "Agent Dashboard", packages_path %>

  <% else %><% current_user.role=="user" %>
  <%= link_to "Traveler Dashboard", home_traveler_dashboard_home_path %>

 <% end %>
 <% 
=end %>
     
      
       <% if user_signed_in? %>
       <% if current_user.has_role? :admin %>
       <%= link_to "Super Admin Dashboard", rails_admin_path %>
       <% elsif current_user.has_role? :agent %>
        <%= link_to "Agent Dashboard", packages_path %>

        <% else %><% current_user.has_role? :traveler %>
        <%= link_to "Traveler Dashboard", home_traveler_dashboard_home_path %>

       <% end %>
            <li>HI <strong><%= current_user.email %></strong></li> 
            <% unless current_user.has_role? :agent or current_user.has_role? :admin or current_user.agents[0] %>
             <li><%= link_to "Become Agent", new_agent_path, :class => 'navbar-link'  %></li>
             <% end %>
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li> 
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li> 
            <% if current_user.has_role? :admin%>
               <%= link_to "Approve",agencies_approval_path %>
           <% end %>
                   
    <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
    <% end %> 
                         
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


  </div>

<div class="container">

<%= yield %>
</div>
  <div id="footer"></div> 

</body>
</html>